### ISSUE TITLE
Chrome extension dashboard url for safe.moe

### ISSUE THREAD

**Issue by riesza** [WeebDev/loli-safe-extension#1]
![wpygd 1](https://cloud.githubusercontent.com/assets/1399263/25579042/93f0cc6e-2e74-11e7-8340-b900dcbc0e24.png)

Clicking this directs you to https://safe.moe/dashboard when the correct url would probably be https://safe.moe/panel

**Comment by Pitu** [comment]
I made the decision back then that the administration interface should be called dashboard instead of panel, and the extension adheres to that. safe.moe decided to use /panel instead, which is fine, but not where the extension points. We'll either add support for typing the correct name on the extension or I'll bug @alucard0134 enough so he adds dashboard as an alias, since that's what lolisafe ships with and everyone who's running it uses, except him.

**Comment by Shumatsu** [comment]
safe.moe no longer uses panel in place of dashboard.
